# Application name
spring.application.name=Food-Waste-Collection-Redistribution

# \u2705 JDBC connection details
spring.datasource.url=jdbc:mysql://localhost:3306/fwcrd_db
spring.datasource.username=root
spring.datasource.password=B.Ganesh@7171
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# \u2705 Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# \u2705 Logging
logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error
logging.level.org.springframework.security=DEBUG


